<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:300,400">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>My Cinema</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css'>
    <link rel='stylesheet prefetch' href='https://fonts.googleapis.com/icon?family=Material+Icons'>
    <link rel="stylesheet" href="../css/styles.css">

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light flex-column">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="d-flex justify-content-left align-items-center ms-4">
                <a class="navbar-brand" href="#">

                </a>
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="index.php">Home</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Categories
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <?php foreach ($cats as $cat) : ?>
                                <a class="dropdown-item" href="index.php?name=<?= $cat['name'] ?>" value="<?= $cat['name'] ?>"> <?= $cat['name'] ?></a>
                            <?php endforeach; ?>
                        </div>
                    </li>


                </ul>


           <form action="index.php" method="GET">
            <input type="datetime-local"  name="from_date" value="2018-01-01T09:30">



                    <input type="datetime-local"  name="to_date" value="2018-01-01T21:30">

                    <button type="submit" class="btn btn-primary">Filter</button>
                </form>
            </div>
            <div class="d-flex mx-4">
                <div class="form-inline my-2 my-lg-0 d-flex align-items-start">
                    <div style="position:relative">
                        <form action="index.php" method="POST">
                            <input id="searchInput" name="title" class="form-control mr-sm-2" type="search" placeholder="Quel film?" aria-label="Rechercher">
                            <ul id="searchList">

                            </ul>
                    </div>
                    <button id="searchBtn" class="btn btn-outline-success my-2 my-sm-0 mx-2" type="submit">Rechercher</button>
                </div>

            </div>
        </div>
    </nav>


    <div class="container">
        <?php foreach ($movies as $movie) { ?>

            <div class="movie-card">
                <div class="movie-header manOfSteel">
                    <div class="header-icon-container">
                        <a href="details.php?id=<?= $movie['id'] ?> " target="_blank">
                            <i class="material-icons header-icon"></i>
                        </a>
                    </div>
                </div>
                <!--movie-header-->
                <div class="movie-content">
                    <div class="movie-content-header">
                        <a href="#">
                            <h3 class="movie-title"><?= $movie['title'] ?></h3>
                        </a>
                        <div class="imax-logo"></div>
                    </div>
                    <div class="movie-info">
                        <div class="info-section">
                            <label>Release Date</label>
                            <span><?= $movie['release_date'] ?></span>
                        </div>
                        <!--date,time-->
                        <div class="info-section">
                            <label>Duration</label>
                            <span>
                                <?= $movie['duration'] ?>
                         
                            </span>
                        </div>
                        <!--screen-->
                        <div class="info-section">
                            <label>Category</label>
                            <span><?= $movie['name'] ?></span>
                        </div>
                        <!--row-->
                    </div>
                </div>
                <!--movie-content-->
            </div>
            <!--movie-card-->
        <?php } ?>

    </div>



    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="./js/main.js"></script>
    <script src="./js/api.js"></script>
</body>

</html>