<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="../css/userlist.css">
    <link rel="stylesheet" href="../css/user_update.css">
    
    <title>History of watched movies </title>
</head>
<body> 
                   
<div class="container rounded bg-white mt-5 mb-5 p-2">
    
           
<div class="container-xl">
    <div class="table-responsive">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">   
                    <div class="col-sm-8"><h1 class="text-left">Profile Settings</h1></div>
            
                </div>
            </div>
            <table class="table table-striped table-hover table-bordered">
                <thead>
                    <tr>
                    <th>Id session</th>
                        <th>Title</th>
                        <th>Date Begin<i class="fa fa-sort"></i></th>
                        <th>Name of room</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach($listmovieschedules  as $listmovies): ?>
                    <tr>
                       <td><?= $listmovies['id'] ?> </td>
                        <td><?= $listmovies['title'] ?> </td>
                        <td> <?= $listmovies['date_begin'] ?> </td>
                        <td> <?= $listmovies['name'] ?> </td>  

                              <td>
                                    <a href="../admin/user_actions.php?id=<?= $user['userid'] ?>" class="view" title="View" data-toggle="tooltip"><i class="material-icons">&#xE417;</i></a>
                                    <a href="../admin/edit.php?id=<?= $user['userid'] ?>" class="edit" title="Edit" data-toggle="tooltip"><i class="material-icons">&#xE254;</i></a>
                                    <a href="#" class="delete" title="Delete" data-toggle="tooltip"><i class="material-icons">&#xE872;</i></a>
                                </td>
                    </tr>
                    
                    <?php endforeach; ?>  
                </tbody>
            </table>
    
        </div>
    </div>  
</div>  
                
   
                <div class="mt-5 text-center"><a href="index.php" class="btn btn-primary profile-button" type="button">Back to List</a></div>
        
            </div>
        </div>

    </div>
</div>
</div>
</div>
</body>
</html>