<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="../css/userlist.css">
    <link rel="stylesheet" href="../css/user_update.css">
    
    <title>History of watched movies </title>
</head>
<body> 
          
<div class="container rounded bg-white mt-5 mb-5 p-2">
    
           
<div class="container-xl">
    <div class="table-responsive">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">   
                    <div class="col-sm-8"><h1 class="text-left">History of watched movies</h1></div>
            
                </div>
            </div>
            <table class="table table-striped table-hover table-bordered">
                <thead>
                    <tr>
                        <th>id</th>
                        <th>List of watched movies <i class="fa fa-sort"></i></th>
                        <th>Viewing date</th>
                        <th>Name of room</th>
                        <th>Floor</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach($userhistory as $history): ?>
                    <tr>
                    <td><?= $history['id'] ?>  </td>
                        <td><?= $history['title'] ?> </td>
                        <td> <?= $history['datemoviesession'] ?> </td>
                        <td> <?= $history['name'] ?> </td>
                
                
                        <td> <?= $history['etage'] ?> </td>
                        
                    </tr>
                    
                    <?php endforeach; ?>  
                </tbody>
            </table>
    
        </div>
    </div>  
</div>  
                
   
                <div class="mt-5 text-center"><a href="index.php" class="btn btn-primary profile-button" type="button">Back to List</a></div>
        
            </div>
        </div>

    </div>
</div>
</div>
</div>
</body>
</html>